### ISSUE TITLE
iThing theme : tick appears out of its container

### ISSUE THREAD

**Issue by nicofrand** [ghusse/jQRangeSlider#105]
The tick might appear outside of its container. Please see the screenshot attached : 
![bug-jqslider](https://f.cloud.github.com/assets/3419050/385202/0afc478a-a679-11e2-8c0d-973523da6273.png)

(In that case, that happened after a dateRangeSlider("bounds", date1, date2).)

A simple CSS code could correct it :

``` CSS
.ui-rangeSlider-innerBar
{
    overflow: hidden;
}
```
